services:
  backend:
    build: ./backend-api
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongo
    env_file:
      - ./backend-api/.env

  worker:
    build: ./worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend-api/src/models:/worker/src/backend-models   # <-- mount models here
    depends_on:
      - redis
      - mongo
    env_file:
      - ./backend-api/.env  # ensures MONGO_URI is available

  redis:
    image: redis:7

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
